apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: guestbook-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frontend-app-pod
      app: guestbook-app
  template:
    metadata:
      name: frontend-app-pod
      labels:
        name: frontend-app-pod
        app: guestbook-app

    spec:
      containers:
      - name: guestboook-app
        image: kubernetes/guestbook:v2
        ports:
        - containerPort: 80