apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-master
    app: frontend-app
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-pod
    app: guestbook-app